[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.28"
via_ir = true

[lint]
exclude_lints = ["screaming-snake-case-immutable"]
ignore = ["contracts/PlonkVerifier.sol"]
